name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before filing a bug, check [existing issues](https://github.com/program-the-brain-not-the-heartbeat/buckit/issues).

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Do ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - Browser / client:
        - Wrangler version:
        - Node version:
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have not included any personal information in this report
          required: true
